version: '3.7'

services:
    # caddy:
    #     image: caddy:2.0.0-alpine
    #     container_name: caddy
    #     volumes:
    #         - '.docker/caddy/:/data'
    #         - '.docker/caddy/Caddyfile:/etc/caddy/Caddyfile'
    #     ports:
    #         - '80:80'
    #         - '443:443'

    nginx:
        build: .docker/nginx/
        container_name: nginx
        volumes:
            - '.docker/nginx/config/:/etc/nginx/sites-enabled/'
            - '.docker/nginx/config/:/etc/nginx/sites-available/'
            - '.docker/nginx/config/:/etc/nginx/conf.d/'
            - './tfe:/var/www'
        ports:
            - ${NGINX_PORT_HTTP}:80
        restart: unless-stopped

    database:
        image: mariadb:10.5.1
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        ports:
            - ${DATABASE_PORT}:3306
        restart: unless-stopped
        container_name: database

    api:
        build: .docker/php/
        container_name: api
        depends_on:
            - database
        volumes:
            - ./tfe:/var/www
            - ./.docker:/var/www/docker
        ports:
            - 9000:9000
        command: "php -S 0.0.0.0:9000 -t /var/www/public"
